# Site settings
baseurl = "https://socrates-fr.github.io/"
languageCode = "en-us"
title = "SoCraTes-FR"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-60791139-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "SoCraTes FRance"
	description = "International Conference for Software Craft and Testing"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
	#
	# What you need to do for the setup?
	#
	# - set your email address under 'email' below
	# - upload the generated site to your server
	# - send a dummy email yourself to confirm your account
	# - click the confirm link in the email from www.formspree.io
	# - you're done. Happy mailing!
	email = "test@gmail.com"
	gforms = "153aAnAaKBsFqusTKXvyZjpgHbKx4LrhPVtn8VubkNKM"

	# Navigation
	[params.navigation]
		brand = "SoCraTes FRance"
		services = "What it is about?"
		portfolio = "Information"
		about = "History"
		team = "Family"
		contact = "Registration"
		sponsors = "Sponsors"

	# Add custom links. Those can be pre- and postpended to the default menu above.
	# Use the weight attribute to order your custom links. Uncomment the example
	# below and replace the values with your own.

	# prepended links
	#[[menu.prepend]]
	#    url = "http://gohugo.io"
	#    name = "Hugo"
	#    weight = 10

	# postpended links
	[[menu.postpend]]
		url = "https://github.com/SoCraTes-FR/socrates-fr.github.io/wiki"
		name = "Wiki"
	[[menu.postpend]]
		url = "/doc/coc.pdf"
		name = "CoC"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "8th Edition of the International Conference for Software Craft and Testing - France. March 20-23th, 2025."
		subtitle="SoCraTes France"
		buttontext = "Tell me more"

	# Services section
	[params.services]
		enable = true
		title = "What it is about?"
		subtitle = "This event is about the sustainable creation of useful software in a responsible way."

		[[params.services.row]]

			[[params.services.row.list]]
				icon = "fa-users"
				title = "It's about People"
				description = "Everyone who is concerned with coding, testing, code quality and craft."

			[[params.services.row.list]]
				icon = "fa-play-circle"
				title = "It's about Action"
				description = "The event will be run as a non-profit, low-cost event. It will be much like a retreat. We will be there for 48 hours to collaborate and share ideas."

			[[params.services.row.list]]
				icon = "fa-plus-circle"
				title = "It's about Fun"
				description = "We will not only spend the days together but also the nights. And – believe it or not – programmers are a great company! There will be be lots of opportunities to spend your time. Starting with simple chilling over hiking and biking, playing games, hanging around, talking, laughing, …"

	# Portfolio section
	[params.portfolio]
		enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Information"
		subtitle = "Information"

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttontext = "Close"


	# About section
	[params.about]
		enable = true
		title = "History"
		subtitle = "Previous and next edition."
		endpoint = "February 2015"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.

		[[params.about.events]]
		img = "3.jpg"
		date = "March 20-23th, 2025"
		title = "Eighth edition"
		description = "It will take place at the beautiful castle 'Château de Massillan' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "October 26-29th, 2023"
			title = "Seventh edition"
			description = "It occurred at the beautiful castle 'Château de Massillan' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "March 17-20th, 2022"
			title = "Sixth edition"
			description = "It occurred at the beautiful castle 'Château de Massillan' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "October 17-20th, 2019"
			title = "Fifth edition"
			description = "It occurred at the beautiful castle 'Château de Massillan' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "October 25-28th, 2018"
			title = "Forth edition"
			description = "It occurred at the beautiful castle 'Château de Massillan' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "October 26-29th, 2017"
			title = "Third edition"
			description = "It occurred at the beautiful castle 'Château de Rochegude' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "October 27-30th, 2016"
			title = "Second edition"
			description = "It occurred at the beautiful castle 'Château de Rochegude' - France (Drôme)"

		[[params.about.events]]
			img = "3.jpg"
			date = "September 2015"
			title = "First Edition"
			description = "It occurred at the beautiful castle 'Château de Rochegude' - France (Drôme)"


	# Team section
	[params.team]
		enable = true
		title = "SoCraTes-FR is a part of a big family."
		subtitle = "The first “Software Craftsmanship and Testing (un)conference” took place a few years ago in Germany and is organised every year since 2011."
		description = "Other conferences have emerged in other European countries such as SoCraTes UK and SoCraTes Canaries."


		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "SoCraTes_FR.png"
			name = "SoCraTes FR"
			position = "France"
			social = [
				["fa-twitter", "https://twitter.com/socrates_fr"],
				["fa-link", "https://socrates-fr.github.io"]
			]

		[[params.team.members]]
			img = "SoCraTes.png"
			name = "SoCraTes"
			position = "Germany"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_Conf"],
				["fa-link", "https://www.socrates-conference.de"]
			]

		[[params.team.members]]
			img = "SoCraTes_UK.png"
			name = "SoCraTes UK"
			position = "United Kingdom"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_UK"],
				["fa-link", "http://socratesuk.org"]
			]

		[[params.team.members]]
			img = "SoCraTes_ES.png"
			name = "SoCraTes Canaries"
			position = "Spain"
			social = [
				["fa-twitter", "https://twitter.com/socracan"],
				["fa-link", "https://www.socracan.org/"]
			]

		[[params.team.members]]
			img = "SoCraTes_CH.jpeg"
			name = "SoCraTes Conf Switzerland"
			position = "Switzerland"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_CH"],
				["fa-link", "http://socrates-ch.org"]
			]

		[[params.team.members]]
			img = "SoCraTesDay_CH.jpeg"
			name = "SoCraTes Day Switzerland"
			position = "Switzerland"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTesDay_CH"],
				["fa-link", "http://socrates-day.ch"]
			]

		[[params.team.members]]
			img = "SoCraTes_BE.png"
			name = "SoCraTes BE"
			position = "Belgium"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_BE"],
				["fa-link", "http://socratesbe.org"]
			]

		[[params.team.members]]
			img = "SoCraTes_IT.png"
			name = "SoCraTes IT"
			position = "Italy"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_Italy"],
				["fa-link", "http://www.socrates-conference.it"]
			]

		[[params.team.members]]
			img = "CodeFreeze.png"
			name = "CodeFreeze"
			position = "Finland"
			social = [
				["fa-twitter", "https://discuss.systems/@codefreeze"],
				["fa-link", "http://www.codefreeze.fi"]
			]

		[[params.team.members]]
			img = "ITAKE.png"
			name = "I T.A.K.E. Unconference"
			position = "Romania"
			social = [
				["fa-twitter", "https://twitter.com/itakeunconf"],
				["fa-link", "http://itakeunconf.com"]
			]

		[[params.team.members]]
			img = "agileCrete.png"
			name = "AgileCrete Unconference"
			position = "Crete, Greece"
			social = [
				["fa-twitter", "https://twitter.com/AgileCrete"],
				["fa-link", "https://agilecrete.org"]
			]

		[[params.team.members]]
			img = "frogs-conf.png"
			name = "Friends of Good Software"
			position = "online from The Netherlands"
			social = [
				["fa-linkedin", "https://www.linkedin.com/company/frogsconf/"],
				["fa-link", "https://frogsconf.nl/"]
			]


	# Sponsor section
	[params.sponsors]
		enable = true
		title = "Our Sponsors"
		subtitle = ""

	[[params.sponsor]]
		name = "CodeWorks"
		logo = "codeworks-square.png"
		link = "https://www.codeworks.fr/"

	[[params.sponsor]]
		name = "Saikoda"
		logo = "saikoda-square.png"
		link = "https://www.saikoda.fr/"

	[[params.sponsor]]
		name = "Malt"
		logo = "malt-square.png"
		link = "https://www.malt.com/"

	[[params.sponsor]]
		name = "Objectware"
		logo = "objectware-square.png"
		link = "https://www.objectware.fr/"

	[[params.sponsor]]
		name = "Kapsul"
		logo = "kapsul-square.jpg"
		link = "https://www.kapsul.io/"

    [[params.sponsor]]
	    name = "McKinsey & Company"
	    logo = "mckinsey-square.png"
	    link = "https://www.mckinsey.com/"

#	[[params.sponsor]]
#		name = "Shodo"
#		logo = "shodo-square.png"
#		link = "https://shodo.io"

#		[[params.sponsor]]
#			name = "La Combe du Lion Vert"
#			logo = "lacombedulionvert-square.png"
#			link = "https://www.lacombedulionvert.fr/"


#		[[params.sponsor]]
#			name = "Edwyn"
#			logo = "edwyn-square.png"
#			link = "https://www.edwyn.tech/"

#		[[params.sponsor]]
#			name = "Wemanity"
#			logo = "wemanity-square.png"
#			link = "https://wemanity.com/"

#		[[params.sponsor]]
#			name = "Octo Technology"
#			logo = "octo-square.png"
#			link = "http://www.octo.com"
#
#		[[params.sponsor]]
#			name = "HackYourJob Community"
#			logo = "hackyourjob-square.png"
#			link = "https://www.hackyourjob.org/"

#		[[params.sponsor]]
#			name = "SOAT"
#			logo = "soat-square.png"
#			link = "http://www.soat.fr"

#		[[params.sponsor]]
#		 	name = "Aneo"
#		 	logo = "aneo-square.jpg"
#		 	link = "http://www.aneo.eu"

# 		[[params.sponsor]]
# 			name = "codecentric"
# 			logo = "codecentric-square.png"
# 			link = "http://www.codecentric.de"

# 		[[params.sponsor]]
#      		name = "Meritis"
#      		logo = "meritis-square.png"
#      		link = "http://meritis.fr"

#		[[params.sponsor]]
#		 	name = "Novencia"
#		 	logo = "novencia-square.png"
#		 	link = "http://www.novencia.com"
#
#		[[params.sponsor]]
#		 	name = "Pix"
#		 	logo = "pix-square.jpg"
#		 	link = "https://pix.fr/"

#		[[params.sponsor]]
#			name = "Alcor.Academy"
#			logo = "alcoracademy-square.png"
#			link = "https://alcor.academy/"

#		[[params.sponsor]]
#		 	name = "Snyk"
#		 	logo = "snyk-square.jpg"
#		 	link = "https://snyk.io"

#	 	[[params.sponsor]]
#	 		name = "Axa"
#	 		logo = "axa-square.jpg"
#	 		link = "https://www.axa.fr"

#		 [[params.sponsor]]
#   		name = "BCG Platinion"
#  			logo = "bcg-square.png"
# 			link = "https://www.bcg.com/"

# 		[[params.sponsor]]
# 			name = "Viseo Technologies"
# 			logo = "viseo-square.jpg"
# 			link = "http://www.viseo.com"

# 		[[params.sponsor]]
# 			name = "Codurance"
# 			logo = "codurance-square.png"
# 			link = "http://codurance.com"

# 		[[params.sponsor]]
#			name = "Orange"
# 			logo = "orange-square.png"
# 			link = "https://developer.orange.com"

# 		[[params.sponsor]]
# 			name = "Zenika"
# 			logo = "zenika-square.jpg"
# 			link = "http://www.zenika.com"

	# Client section
	[params.clients_list]
		enable = false

		# All the clients' logos are stored under 'static/img/logos'.
		# Replace them with your clients's logos.
		[[params.clients]]
			logo = "test.jpg"
			link = "http://www.test.fr"

	[params.socratesday]
		enable = true
		title = "Socrates Day France"
		subtitle = ""
		description = "SoCraTes Day is an International Conference for Software Craft and Testing, a single-day version of the full SoCraTes Conferences. It provides an ideal setting for speaking to and coding with other talented and engaged developers, letting us learn from and with each other."

		[[params.socratesday.members]]
			img = "socratesrenne.png"
			name = "SoCraTes-FR Rennes"
			position = "Rennes"
			social = [
				["fa-twitter", "https://twitter.com/socratesday_fr"],
				["fa-link", "https://socrates-rennes.github.io"]
			]

		[[params.socratesday.members]]
			img = "alpescraft.png"
			name = "AlpesCraft | SoCraTes-FR Grenoble"
			position = "Grenoble"
			social = [
				["fa-twitter", "https://twitter.com/AlpesCraft"],
				["fa-link", "https://www.alpescraft.fr/"]
			]

		[[params.socratesday.members]]
			img = "helloworldnantes.png"
			name = "Hello World Nantes"
			position = "Nantes"
			social = [
				["fa-twitter", "https://twitter.com/helloworldconf"],
				["fa-link", "https://www.hello-world.events/"]
			]


	[params.contact]
		enable = true
		title = "Registration"
		subtitle  = ""
		buttontext = ""
		explains = "Registration is now open."
		#explains = "Pre-registration is now open. If the number of participants exceeds 50, a random draw will be held on the end of May."

	# Footer section
	[params.footer]
		enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/SoCraTes_FR/"
